spring:
  application:
    name: gateway
   
eureka:  client:    service-url:      defaultZone: http://localhost:8787/eureka
      
zuul:  routes:    proxy:
      path: /p/**
      serviceId: proxy
    catalog:
      path: /catalog/**
      serviceId: catalog
     